### ISSUE TITLE
Rename this resource module to WebAdministrationDsc

### ISSUE THREAD

**Issue by mbreakey3** [dsccommunity/WebAdministrationDsc#213]
Looking for any and all feedback on the first release of [WebAdministrationDsc](https://github.com/PowerShell/xWebAdministration/tree/WebAdministrationDsc)!

**Comment by hahndorf** [comment]
Hi Mariah,
maybe you could first explain what this is. Is it the first step of moving xWebAdministration to WebAdministration which will eventually become a part of WMF 5.x rather than a downloadable resource kit? Why did you pick those three resources over the others? 

If you want some feedback, please explain what you are trying to do first.

**Comment by PlagueHO** [comment]
Hi @hahndorf  - this relates to the DSC [HQRM programme](https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md). All resources in the xWebAdministration kit are going to be reworked so that the meet the HQRM guidelines.

Also, there was some discussion around this in the community calls:
https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/06-30-16/Notes.md#high-quality-resource-modules
https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/08-03-16/Notes.md#high-quality-web-administration-partial-release

HTH

**Comment by hahndorf** [comment]
@PlagueHO - Thanks, that's helpful information.

**Comment by mbreakey3** [comment]
Thank you responding @PlagueHO!  @hahndorf - the reason we chose these resources for the first release is simply because they required the least amount of work to get them to High Quality and we wanted to get a preview out as soon as possible. The rest of the resources in xWebAdministration will be updated as soon as I and the other maintainers have time. Currently [xPSDesiredStateConfiguration](https://github.com/PowerShell/xPSDesiredStateConfiguration) is our top priority.

**Comment by mbreakey3** [comment]
But any feedback on these resources is of course still welcomed and encouraged

**Comment by johlju** [comment]
This issue should be refocused to do the rename as the other resource module are renamed, the entire resource module should be renamed. This is in progress in the working branch in this repo, that branch should be pulled into a new working branch (in the fork of whomever take this on) that renames this entire resource module to WebAdministrationDsc.

I have changed the title and relabelled this issue to reflect this so that anyone in the community can run with this!
