### ISSUE TITLE
xWebfarm: New resource proposal

### ISSUE THREAD

**Issue by xunilrj** [dsccommunity/WebAdministrationDsc#29]
Hi, I am planning (actually have already started) to create the resource to control ARR webfarm.

One can see the progress at:
https://github.com/xunilrj/xWebAdministration/network
https://github.com/xunilrj/xWebAdministration/tree/feature/MSFT_xWebfarm/DSCResources/MSFT_xWebfarm

Does someone thinks that would be useful?

**Comment by tysonjhayes** [comment]
I'm of the opinion that if it can be configured in IIS then it should have some kind of resource for it.

Some quick suggestions I would make would be add some tests and documentation (examples) of how to use the code. Personally I'd never heard of a web farm in this regard before so I had to do some searching to figure out what it was you were doing.

As for if someone thinks it would be useful, well you did, which is why you made it. So I'm sure someone else will!

**Comment by tysonjhayes** [comment]
Hi @xunilrj did you want to submit a pull request on this?

**Comment by xunilrj** [comment]
I would love to do the PR. I will just finish some adjustments and send it.

**Comment by xunilrj** [comment]
I made the PR and it is ready for review:
https://github.com/PowerShell/xWebAdministration/pull/103

**Comment by mbreakey3** [comment]
Can this issue be closed?

**Comment by johlju** [comment]
I have marked the PR #13 as abandoned so that someone else can continue the work.
