### ISSUE TITLE
Confusing package names in PowerShell Gallery

### ISSUE THREAD

**Issue by davetapley** [dsccommunity/WebAdministrationDsc#614]
Since #601 it is confusing that the package name on PowerShell Gallery wasn't updated:
https://www.powershellgallery.com/packages/xWebAdministration/

And to make matters worse there is **already another package with the new name** 😞 :
https://www.powershellgallery.com/packages/WebAdministrationDsc/

... but at least only one version and last pushed in 2016.

---

Perhaps ⬇️ and ask if `WebAdministrationDsc` can be surrendered to this package?
https://www.powershellgallery.com/packages/WebAdministrationDsc/0.1.0.0/ContactOwners

**Comment by johlju** [comment]
Ah, I have waited for @gaelcolas to fix the API key because the deploy failed. I did not know the PowerShell Team published that module to the Gallery, and of course that is why the deploy fails. 😕 
It was done work way back (several years) to move the module to *Dsc name that never happened, or so I thought...

Let's try to see if we can get that package transferred to DSC Community.

Thanks for making me aware of this!

**Comment by johlju** [comment]
It seems the old WebAdministrationDsc module is from this (now obsolete) working branch https://github.com/dsccommunity/WebAdministrationDsc/tree/WebAdministrationDsc.

**Comment by sebug** [comment]
Hello folks, I'm looking forward to using the WebAdministrationDsc module, is there anything I can do to help resolve this naming issue?

**Comment by johlju** [comment]
We have gotten an okey for DSC Community take over the module in PSGallery. We are now waiting for the transfer to happen, after that will hastily release the new version that is waitin gin this repo.

**Comment by johlju** [comment]
Now WebAdministrationDsc has been released: https://twitter.com/dsccommunity/status/1571195505014894592
